name: LavaRises
version: '1.0'
main: sleaky.lavaRises.LavaRises
api-version: '1.21'
commands:
  startlavarises:
    usage: /startlavarises <MapSize> <seed> <TimeBetweenEachLavaRise> <TimeUntilPvP>
    description: Starts the game with an optional setSeed
    permission: LavaRises.start
  stopgame:
    usage: /stopgame
    description: Stops the game
    permission: LavaRises.stop
  help:
    usage: /help
    description: Shows available commands and their usage